micronaut:
  application:
    name: dent
  server:
    default-charset: UTF-8
    idle-timeout: 50m
    port: 8090
  router:
    static-resources:
      css:
        paths: classpath:/web/css
        mapping: /css/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /gcg/swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /gcg/swagger-ui/**
  executors:
    io:
      type: fixed
      nThreads: 75
#    scheduled:
#      type: scheduled
#      core-pool-size: 30
  http:
    client:
      read-timeout: 30s
  views:
    soy:
      enabled: false
    rocker:
      enabled: false
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/dent
    username: ${JDBC_USER:dent}
    password: ${JDBC_PASSWORD:dent}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    packages-to-scan:
      - 'gcg.dent.entity'
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: none
        show_sql: false