micronaut:
  application:
    name: dent
  server:
    default-charset: UTF-8
    idle-timeout: 50m
    port: 8090
  #router:
    #static-resources:
      #swagger:
        #paths: classpath:META-INF/swagger
        #mapping: /dent/swagger/**
      #swagger-ui:
        #paths: classpath:META-INF/swagger/views/swagger-ui
        #mapping: /dent/swagger-ui/**
  executors:
    io:
      type: fixed
      nThreads: 75
#    scheduled:
#      type: scheduled
#      core-pool-size: 30
  http:
    client:
      read-timeout: 30s
  views:
    soy:
      enabled: false
    rocker:
      enabled: false